version: "3"

networks:
    app-network:
services:
    database:
        image: mysql:8
        container_name: ${PROJECT_NAME}-database
        hostname: ${PROJECT_NAME}-database
        restart: always
        environment:
            - TERM=xterm
            - MYSQL_ALLOW_EMPTY_PASSWORD=no
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./mysql/entrypoint:/docker-entrypoint-initdb.d
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            - app-network
    app:
        build:
            context: .
            dockerfile: app.dockerfile
        container_name: ${PROJECT_NAME}-app
        volumes:
            - ${PROJECT_PATH}:/var/www/html
        ports:
            - ${WEB_SERVICE_PORT}:80
        networks:
            - app-network
    pma:
        image: phpmyadmin/phpmyadmin
        container_name: ${PROJECT_NAME}-pma
        hostname: ${PROJECT_NAME}-pma
        environment:
            - TERM=xterm
            - PMA_HOST=xproduct-database
            - PMA_USER=root
            - PMA_PASSWORD=root
        restart: always
        ports:
            - ${PMA_SERVICE_PORT}:80
        networks:
            - app-network
